version: '2'

networks:
  main:
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

services:
  bootnode:
    build: thebootnode
    networks:
      main:
        ipv4_address: 172.21.0.2

  geth:
    build: theminernode
    networks:
      - main
    ports:
      - "8545:8545"
    depends_on:
      - bootnode
    links:
      - netstats
    environment:
      MINE_WHEN_NEEDED: "true"
    command:
      --networkid 90210
      --port 30303
      --rpc
      --rpcport 8545
      --rpcaddr 0.0.0.0
      --rpcapi "eth,web3,admin,db,net,miner,personal"
      --rpccorsdomain="*"
      --unlock 0
      --password /home/geth_user/.ethereum/passwords
    volumes:
      - ./data:/home/geth_user/.ethereum:rw

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    networks:
      - main
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

  ipfs:
    container_name: ipfs
    hostname: ipfs
    image: ipfs/go-ipfs:latest
    restart: on-failure
    networks:
      - main
    volumes:
      - ./ipfs-storage/export:/export
      - ./ipfs-storage/data:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
