version: '2'

networks:
  main:
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

services:
  bootnode:
    build: thebootnode
    #image: ahannigan/geth-dev:bootnode
    networks:
      main:
        ipv4_address: 172.21.0.2

  geth:
    #image: ahannigan/geth-dev:latest
    build: theminernode
    networks:
      - main
    ports:
      - "8545:8545"
    depends_on:
      - bootnode
    links:
      - netstats
    environment:
      MINE_WHEN_NEEDED: "true"
    command:
      --networkid 90210
      --port 30303
      --rpc
      --rpcport 8545
      --rpcaddr 0.0.0.0
      --rpcapi "eth,web3,admin,db,net,miner,personal"
      --rpccorsdomain="*"
      --unlock 0
      --password /root/.ethereum/passwords
    volumes:
      - ./data:/root/.ethereum:rw

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
